name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  debug:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true  # Only you can access the session

  x86:
    name: x86_64 (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust + Clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          toolchain: 1.83.0
      - name: Clippy (x86)
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Test (x86)
        run: cargo test --all-targets --all-features -- --test-threads=1

  arm:
    name: ️‍ ARM64 (ubuntu-24.04-arm)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust + Clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.83.0
      - name: Test (ARM)
        run: cargo test --all-targets --all-features -- --test-threads=1